Name: Build Geode Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ“‚
        uses: actions/checkout@v4

      - name: Build Mod ğŸ› ï¸
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly
          # Combinamos la plataforma con las arquitecturas comunes
          target: Android32 Android64
          # Esto asegura que las herramientas de Android (NDK) se configuren
          install-binaries: true

      - name: Guardar Mod ğŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Android-Miku
          # Es mejor especificar una ruta mÃ¡s clara si es posible, 
          # pero esta bÃºsqueda funciona bien.
          path: "./build/*.geode"

