name: Build Geode Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ“‚
        uses: actions/checkout@v4

      - name: Build Mod ğŸ› ï¸
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly
          # Usamos comillas para que reconozca ambos targets correctamente
          target: "Android32 Android64"
          # Eliminamos install-binaries para quitar el Warning

      - name: Guardar Mod ğŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Android-Miku
          path: "**/*.geode"
          
