name: Build Geode Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/setup-geode@v2

      - name: Build Mod
        # Aquí es donde añadimos manualmente la plataforma que faltaba
        run: |
          geode sdk install-binaries
          geode build --platform android --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Mod-Package
          path: "**/*.geode"

