name: Build Geode Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ðŸ“‚
        uses: actions/checkout@v4

      - name: Instalar Geode ðŸ”§
        run: |
          # 1. Descargamos el CLI ðŸ“¥
          wget https://github.com/geode-sdk/cli/releases/download/v3.7.1/geode-cli-v3.7.1-linux.zip
          unzip geode-cli-v3.7.1-linux.zip
          chmod +x geode
          sudo mv geode /usr/local/bin/geode

      - name: Compilar para Android ðŸš€
        run: |
          # 2. Saltamos la creaciÃ³n manual y vamos directo al grano ðŸ”¨
          # Usamos --platform android en TODO para que no entre en pÃ¡nico
          geode sdk install-binaries --platform android
          geode build --platform android --release

      - name: Guardar Mod ðŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Android-Miku
          path: "**/*.geode"

          
