name: Build Geode Android

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ“‚
        uses: actions/checkout@v4

      - name: Setup Geode âš™ï¸
        uses: geode-sdk/build-geode-mod@main
        with:
          # Solo lo usamos para instalar el SDK, no para compilar todavÃ­a
          install-binaries: true
          sdk: nightly
          # AquÃ­ estÃ¡ el truco: le pasamos el argumento crudo ğŸ‘Š
          build-args: --platform android
          target: Android

      - name: Upload Artifact ğŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Android
          path: "**/*.geode"
          
