name: Build Geode Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ“‚
        uses: actions/checkout@v4

      - name: Instalar CLI ğŸ”§
        run: |
          wget https://github.com/geode-sdk/cli/releases/download/v3.7.1/geode-cli-v3.7.1-linux.zip
          unzip geode-cli-v3.7.1-linux.zip
          chmod +x geode
          sudo mv geode /usr/local/bin/geode

      - name: Preparar Entorno âš™ï¸
        run: |
          # Creamos el perfil sin que Linux intente ejecutar el nombre
          geode profile add --name "miku" .
          # Seteamos la plataforma ANTES de instalar nada
          geode config set default-platform "android"

      - name: Compilar ğŸ“±
        run: |
          geode sdk install-binaries
          # Usamos comillas para evitar el error de 'command not found'
          geode build --platform "android" --release

      - name: Guardar Mod ğŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Android
          path: "**/*.geode"

          
