name: Build Geode Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Mod (Manual)
        uses: geode-sdk/build-geode-mod@main
        with:
          # Esta es la Ãºnica forma de que no ignore la plataforma:
          # Se la pasamos como un argumento directo al CLI
          build-args: --platform android
          install-binaries: true
          combine: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Package
          path: "**/*.geode"
