name: Build Geode Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Geode CLI
        run: |
          curl -L https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-linux.zip -o geode-cli.zip
          unzip geode-cli.zip
          chmod +x geode
          sudo mv geode /usr/local/bin/geode

      - name: Build Mod
        run: |
          geode sdk install-binaries
          # Aqu√≠ forzamos la plataforma manualmente
          geode build --platform android --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Package
          path: "**/*.geode"
          
          
