name: Build Geode Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Geode CLI
        run: |
          wget https://github.com/geode-sdk/cli/releases/latest/download/geode-cli-linux.zip
          unzip geode-cli-linux.zip
          chmod +x geode
          sudo mv geode /usr/local/bin/geode

      - name: Setup SDK and Build
        run: |
          geode sdk install-binaries
          # Aqu√≠ escribimos MANUALMENTE la plataforma para que no haya error
          geode build --platform android --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Mod
          path: "**/*.geode"
          
