name: Build Geode Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # Esto instala el SDK de Android y de Geode correctamente
          install-binaries: true
          # Forzamos los argumentos para que CMake los reciba
          build-args: --platform android
          combine: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Mod
          path: "**/*.geode"
          
