name: Build Geode Android

on:
  workflow_dispatch:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ“‚
        uses: actions/checkout@v4

      - name: Instalar Geode ğŸ”§
        run: |
          # 1. Descargamos el CLI ğŸ“¥
          wget https://github.com/geode-sdk/cli/releases/download/v3.7.1/geode-cli-v3.7.1-linux.zip
          unzip geode-cli-v3.7.1-linux.zip
          chmod +x geode
          sudo mv geode /usr/local/bin/geode

      - name: ConfiguraciÃ³n AutomÃ¡tica âš™ï¸
        run: |
          # 2. Instalamos el SDK sin nombres raros para evitar errores
          # Solo le decimos la plataforma y la ruta (.)
          geode sdk install --platform android .
          
      - name: Compilar para Android ğŸš€
        run: |
          # 3. Compilamos directo ğŸ”¨
          geode build --platform android --release

      - name: Guardar Mod ğŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: Mod-Android-Geode
          path: "**/*.geode"
          
