name: Build Geode Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/setup-geode@main

      - name: Install SDK Binaries
        run: geode sdk install-binaries

      - name: Configure and Build
        # Aqu√≠ forzamos manualmente la plataforma y el generador
        run: |
          geode build --platform android --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-Mod
          path: "**/*.geode"
